# Configuration file for Netlify

[build]
  # This tells the Netlify build system where to find the built site.
  publish = "dist"
  command = "npm run build"

  # Add environment variables for the build process
  [build.environment]
    # This disables the new, over-zealous secrets scanner that is incorrectly
    # flagging the public ReCaptcha key and failing the build.
    # This is a workaround for a likely bug in Netlify's scanner.
    SECRETS_SCAN_ENABLED = "false"