// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://samojjxvizkiqzhtewfs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNhbW9qanh2aXpraXF6aHRld2ZzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM3NTAxNDAsImV4cCI6MjA2OTMyNjE0MH0.4u2X8jJjcs5DcJCqEiolLa7iH4N3eZcCX8ICojvUQl8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});